### PR TITLE
Fix title trim to 191 and add exception for to long slug

### LINKED ISSUE #39: ArticlePersister and PagePersister silently truncate titles to 64/63 characters
Bundle version: 1.0.0-RC3                                       
                                                                                                           
  Description                                                     

  During PHPCR migration, article and page titles are silently truncated using str_split():                
   
  - ArticlePersister.php:62: $data['title'] = \str_split((string) $data['title'], 64)[0];                  
  - PagePersister.php:68: $data['title'] = \str_split((string) $data['title'], 63)[0] ?? '';
                                                                                                           
  The target database columns are VARCHAR(191), so there is no database constraint requiring this          
  truncation. Titles up to 191 characters should be preserved intact.                                      
                                                                                                           
  Impact                                                          
                                                                  
  The truncation is silent — no warning or error is logged. The templateData JSON column also receives the 
  truncated title (line 63/69), so the title is lost in both the title column and the JSON blob.           
                                                                     
  Steps to reproduce                                                                                       
   
  1. Have a Sulu 2.6 installation with articles/pages whose titles exceed 64 characters                    
  2. Run php bin/adminconsole sulu:phpcr-migration:migrate article
  3. Check ar_article_dimension_contents.title — all titles are truncated to 64 characters                 
                                                                                                           
  Expected behavior                                                                                        
                                                                                                           
  Titles should be migrated without truncation (up to the column limit of 191 characters).                 
                                                                  
  Suggested fix                                                                                            
                                                                  
  Remove the str_split() calls:

  // ArticlePersister.php:61-64
   if (isset($data['title'])) {                                                                            
  -    $data['title'] = \str_split((string) $data['title'], 64)[0];
  +    $data['title'] = \mb_substr((string) $data['title'], 0, 191);                                       
       $data['templateData']['title'] = $data['title'];                                                    
   }                                                                                                       
                                                                                                           
  // PagePersister.php:66-70                                      
   if (isset($data['title'])) {
  -    // TODO error collector with titles that were too long
  -    $data['title'] = \str_split((string) $data['title'], 63)[0] ?? '';                                  
  +    $data['title'] = \mb_substr((string) $data['title'], 0, 191);
       $data['templateData']['title'] = $data['title'];                                                    
   }                                                              
                                                                                                           
  If there is a reason for the truncation (e.g. a column constraint in an earlier Sulu 3.0 version), it should at least log a warning.

 Environment
  - sulu/phpcr-migration-bundle: 1.0.0-RC3
  - sulu/sulu: 3.0.4                      
  - PHP: 8.4        
  - MySQL: 8.0

### PR DESCRIPTION
**Pull request by martinlagler**
Update title trim to 191 and add exception for to long slug.
No error collector because in Sulu 2.6 title also had a maximum length.

Fixes https://github.com/sulu/SuluPHPCRMigrationBundle/issues/39

### CODE REVIEW

File: PhpcrMigration/Application/Exception/SlugTooLongException.php [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+ */
+
+namespace Sulu\Bundle\PhpcrMigrationBundle\PhpcrMigration\Application\Exception;
+
+class SlugTooLongException extends \RuntimeException
+{
+    public function __construct(string $slug, string $uuid, string $locale)
+    {
+        parent::__construct(\sprintf(
+            'Slug "%s" for document "%s" (locale: %s) exceeds the maximum length of 144 characters.',
```
Comment (Prokyonn) [inline PhpcrMigration/Application/Exception/SlugTooLongException.php]: can we extract the 144 to an constant and use it here and in the validation logic

File: PhpcrMigration/Application/Exception/TitleTooLongException.php [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+ */
+
+namespace Sulu\Bundle\PhpcrMigrationBundle\PhpcrMigration\Application\Exception;
+
+class TitleTooLongException extends \RuntimeException
+{
+    public function __construct(string $title, string $uuid, ?string $locale)
+    {
+        parent::__construct(\sprintf(
+            'Title "%s" for document "%s" (locale: %s) exceeds the maximum length of 191 characters.',
```
Comment (Prokyonn) [inline PhpcrMigration/Application/Exception/TitleTooLongException.php]: can we extract the 191 to an constant and use it here and in the validation logic

**Review by Prokyonn — CHANGES_REQUESTED** [review]
