### PR TITLE
Fix permission query for postgresql

### LINKED ISSUE #25: Problem with Migrate Permission Contexts query
With the latest Sulu 3 plus also the new release of this migration bundle, when I run:

```
bin/adminconsole sulu:phpcr-migration:migrate
```

I get the following error:

```
Migrating snippet_area documents
================================

Migrating snippet_area documents in default
-------------------------------------------

 4/4 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100% < 1 ms/< 1 ms 174.5 MiB


In MigratePermissionContextsQuery.php line 90:
                                          
  Warning: Undefined array key "idRoles"  
                                          

sulu:phpcr-migration:migrate [<documentTypes>]
```

### PR DESCRIPTION
**Pull request by Prokyonn**
Should fix https://github.com/sulu/SuluPHPCRMigrationBundle/issues/25

### CODE REVIEW

File: PhpcrMigration/Application/Query/MigratePermissionContextsQuery.php [hunk 1]
```diff
@@ -86,20 +92,25 @@ private function migrateSnippetPermissions(Connection $connection): void
...
+                'idRoles' => $roleId,
+            ]);
 
             if (!$exists) {
-                $connection->insert('se_permissions', [
-                    'context' => self::SNIPPET_AREA_CONTEXT,
-                    'permissions' => self::ARCHIVE_PERMISSION,
-                    'idRoles' => $roleId,
-                ]);
+                $this->entityRepository->insertOrUpdate(
```
Comment (alexander-schranz) [inline PhpcrMigration/Application/Query/MigratePermissionContextsQuery.php]: can we add a `insert` here as I think this case doesn't make sense as it never uses `Update` or `exists` functionality of `insertOrUpdate` as it does that check itself?
